version: '3.8'
networks:
  traefik-net:
    external: true
services:
  peario-server:
    build: .
    ports:
      - "3001:8181"
    networks:
      - traefik-net
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pearioserver.rule=Host(`peario-server.84.8.135.166.sslip.io`)"
      - "traefik.http.services.pearioserver.loadbalancer.server.port=8181"